### PR TITLE
show latest posts first and added default error image

### LINKED ISSUE #4: sort the posts according to date " latest post first "

### PR DESCRIPTION
**Pull request by rootaux**
**Description of PR**

To fix this issue, I created a duplicate array using slice and then reversed it and by doing this the react state does not change at all.

**Relevant Issues**  
Fixes #4 

**Checklist**

- [ x] Compiles and passes lint tests
- [ x] Properly formatted
- [ x] Tested on desktop
- [ x] Tested on phone

**Screenshots**
Add relevant screenshots here
Updated Homepage

### CODE REVIEW

**Comment by rootaux** [comment]
Added a new commit which fixes #2 
**Edit**: Added screenshot
Added default error image

**Comment by Pandimadhubabu** [comment]
can we use this https://github.com/React757/web to get images ( open graph data)

**Comment by rootaux** [comment]
> can we use this https://github.com/React757/web to get images ( open graph data)

I'm not quite sure what you mean? There isn't much on the readme file.

**Comment by Pandimadhubabu** [comment]
soure

> > can we use this https://github.com/React757/web to get images ( open graph data)
> 
> I'm not quite sure what you mean? There isn't much on the readme file.

source of this site https://chickar.ee/

**Comment by rootaux** [comment]
@Pandimadhubabu You want feeds of different websites and for each feed users can check their latest posts and follow it if they like. Is this correct?

**Comment by rootaux** [comment]
Actually on checking #9 I understand what you want. But since you are getting your data from a json you would have to add a new field in your response schema for excepts and images. Also if I under correctly you are adding all these links to a Google spreadsheet and converting it into json, so why not add another column for it?

**Comment by Pandimadhubabu** [comment]
> Actually on checking #9 I understand what you want. But since you are getting your data from a json you would have to add a new field in your response schema for excepts and images. Also if I under correctly you are adding all these links to a Google spreadsheet and converting it into json, so why not add another column for it?

https://docs.google.com/spreadsheets/d/1VIgWeByW0t2CEQA5Sssrze48V_R6wemDV6ws7S-FSgc/edit#gid=1248494042

**Pull request merged**
